stages:
  - code-lint
  - git-check

# code-lint 阶段：运行 ./mvnw spotless:check 进行代码格式检查
code-lint:
  stage: code-lint
  image: hub-poseidon.cisdigital.cn/mirror/gitlab-ci-cd:1.0.0
  script:
    - ./mvnw spotless:check  # 检查代码格式
  only:
    - merge_requests  # 只在 MR 创建或更新时运行

# git-check 阶段：检查 commit-msg 和是否 squash
git-check:
  stage: git-check
  image: hub-poseidon.cisdigital.cn/mirror/gitlab-ci-cd:1.0.0
  before_script:
    - python3 -v
  script:
    - python3 .gitlab-ci/git-check.py  # 运行我们写的 Python 校验脚本
  only:
    - merge_requests  # 只在 MR 创建或更新时运行
  when: on_failure  # 如果失败时直接关闭 MR