fail_fast: true
default_install_hook_types:
  - commit-msg
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: spotless-apply
        name: 统一代码风格
        stages:
          - pre-commit
        entry: python3 ./scripts/spotless_apply.py
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: check-commit-message
        name: 校验提交信息
        stages:
          - commit-msg
        entry: python3 ./scripts/validate_commit_msg.py
        language: system
